name: "build"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      - name: install
        run: |
          python -m pip install --upgrade pip setuptools six wheel
          python -m pip install mypy pytest -r requirements.txt
      # - run: mypy --ignore-missing-imports --install-types --non-interactive .
      # - name: run testing problem test
      #   run: pytest deutsch_algorithm/deutsch.py --doctest-modules
        
